version: '3.4'

services:
    hoteldb:
        container_name: hoteldb
        restart: always
        volumes: 
          - ${WEBAPP_STORAGE_HOME}/site:/data/db
        ports:
          - "27017:27017"
    hotelmanager:
        container_name: hotelmanager
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_URLS=https://+:443;http://+:80
          - "HotelDbSettings:ConnectionString=mongodb://hoteldb:27017"
        depends_on:
          - hoteldb
        ports:
          - "80"
          - "443"
        volumes:
          - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
          - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro